name: kadu_booking_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
  flutter: ">=2.8.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.24.2
  cloud_firestore_platform_interface: ^6.0.3
  google_fonts: 4.0.4
  go_router: ^12.1.0
  connectivity_plus: ^5.0.1
  fluttertoast: ^8.2.4
  flutter_form_builder: ^8.0.0
  get: ^4.6.6
  # cloud_firestore: ^4.12.2
  hexagon: ^0.2.0
  carousel_slider: ^4.2.1
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.1.5
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  geolocator: ^7.6.2
  pdf: ^3.10.6
  url_launcher: ^6.2.1
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.1.1
  intl: ^0.17.0
  table_calendar: ^3.0.8
  syncfusion_flutter_datepicker: ^21.2.3
  pinput: ^3.0.1
  g_recaptcha_v3: ^0.0.5
  # http: ^1.1.0
  provider: ^6.1.1
  share: ^2.0.4
  http: ^0.13.0-nullsafety.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  cached_network_image: ^3.3.0
  flutter_signature_pad: ^3.0.1
  flutter_google_places: ^0.3.0
  location: ^5.0.3
  transparent_image: ^2.0.1
  flutter_image_compress: ^2.1.0
  maps_places_autocomplete: ^0.0.2
  socket_io_client: ^2.0.3+1
  shelf: ^1.4.1
  image: ^4.1.3
  favorite_button: ^0.0.4
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.5
  substring_highlight: ^1.0.33
  google_places_autocomplete_text_field: ^0.1.2
  photo_view: ^0.14.0
  clean_calendar: ^1.1.0
  calendar_date_picker2: ^0.5.3
  screenshot: ^2.1.0
  syncfusion_flutter_pdf: ^21.2.4
  device_info_plus: ^9.1.1
  awesome_notifications: ^0.7.4+1
  flutter_launcher_icons: ^0.13.1
  image_gallery_saver: ^2.0.3
  signature: ^5.4.1
  dio: ^5.4.0
  pdfx: ^2.4.0
  advance_pdf_viewer: ^2.0.1
  badges: ^3.1.2
  printing: ^5.11.1
  flutter_pdfview: ^1.3.2
  firebase_messaging: ^14.7.10
  flutter_phone_direct_caller: ^2.1.1
  open_mail_app: ^0.4.5
  open_file: ^3.3.2
  flutter_to_pdf: ^0.1.1
  rate_in_stars: ^0.0.3
  multi_image_picker: ^4.8.01
  photo_manager: ^2.8.1
  multiple_images_picker: ^1.0.1
  flutter_rating_bar: ^4.0.1
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  phone_form_field: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  rxdart: ^0.26.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/
    # - packages/flutter_google_places/assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"