name: kadu_booking_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  cloud_firestore_platform_interface: ^6.0.3
  firebase_core_platform_interface: ^5.0.0
  firebase_app_check: ^0.2.1+3
  firebase_messaging: ^14.7.3
  firebase_auth_platform_interface: ^7.0.3
  google_fonts: ^6.1.0
  go_router: ^12.1.0
  connectivity_plus: ^5.0.1
  fluttertoast: ^8.2.2
  flutter_form_builder: ^8.0.0
  get: ^4.6.6
  cloud_firestore: ^4.12.2
  hexagon: ^0.2.0
  carousel_slider: ^4.2.1
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  geolocator: ^7.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/